---
- name: deployment
  hosts: all
  become: true
  vars:
    nexus_url: http://ec2-65-1-145-213.ap-south-1.compute.amazonaws.com:8081/repository
    repository_type: java-maven-war-app-release
    group_id: com%2Fmycompany%2Fapp
    artifact_id: hello-world-war
    version: 2.0.0
    build_number: "{{build_number}}"
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "{{nexus_url}}/{{repository_type}}/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war"
      dest: /home/ec2-user/saravana
      username: admin
      password: abc123

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/saravana/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war /home/ec2-user/saravana/hello-world.war

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/saravana/hello-world.war /opt/apache-tomcat-9.0.90/webapps/hello-world.war

  - name: remove the artifact
    ansible.builtin.shell: rm -rf /home/ec2-user/saravana/hello-world.war



