---
- name: deployment
  hosts: all
  become: true

  vars:
    nexus_url: http:ec2-15-206-90-4.ap-south-1.compute.amazonaws.com:8081/repository
    repository_type: java-maven-war-app-release
    group_id: com%2Fmycompany%2Fapp
    artifact_id: hello-world-war
    version: 2.0.0
    build_number: 47
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: http://15.206.90.4:8081/repository/java-maven-war-app-release/com/mycompany/app/hello-world-war/2.0.0-47/hello-world-war-2.0.0-47.war
     # url: "{{nexus_url}}/{{repository_type}}/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war"
      dest: /home/ec2-user
      username: admin
      password: abc123

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/hello-world-war-2.0.0-47.war  /home/ec2-user/faangler.war

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/faangler.war /opt/apache_tomcat/webapps/faangler.war

  - name: remove the artifact
    ansible.builtin.shell: rm -rf /home/ec2-user/faangler.war



